services:
  - type: web
    name: telegram-store-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: CRYPTO_PAY_TOKEN
        sync: false
      - key: BINANCE_PAY_ID
        sync: false
      - key: WEBAPP_URL
        sync: false
